name: durham_environmental_monitoring
version: '1.0'
profile: default
config-version: 2
model-paths: ["transformations/dbt/models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  durham_environmental_monitoring:
    +materialized: view

# Add additional dbt configuration as needed
