version: 2
sources:
  - name: raw_sources
    description: Raw ingestion tables from sensor pipelines
    schema: sensors
    freshness:
      warn_after: {count: 26, period: hour}
      error_after: {count: 36, period: hour}
    loaded_at_field: timestamp
    tables:
      - name: wu_raw_materialized
        description: Weather Underground raw observations
        loaded_at_field: timestamp
      - name: tsi_raw_materialized
        description: TSI device raw observations
        loaded_at_field: timestamp
