# This workflow uses 'uv' to speed up testing and linting.

name: Python application test with Ruff and Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # The official action to install uv. It's very fast.
    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Install dependencies
      run: |
        # Create a virtual environment
        uv venv
        # Install dependencies from the requirements file.
        # 'sync' is much faster than 'pip install'.
        uv pip sync requirements-dev.txt

    - name: Scan for vulnerabilities with pip-audit
      run: |
        # 'uv run' executes a command within the virtual environment.
        uv run pip-audit

    - name: Lint with ruff
      run: |
        uv run ruff check .

    - name: Test with pytest
      run: |
        uv run python -m pytest tests/unit tests/integration
      env:
        PYTHONPATH: ${{ github.workspace }}/src