# This is a basic workflow to help you get started with Actions.

name: Python application test with Ruff and Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip setuptools
        pip install -r requirements-dev.txt
        pip install pip-audit
        pip install ruff

    - name: Scan for vulnerabilities
      run: |
        source .venv/bin/activate
        pip install pip-audit
        pip-audit

    - name: Lint with ruff
      run: |
        source .venv/bin/activate
        ruff check .

    - name: Test with pytest
      run: |
        PYTHONPATH=$GITHUB_WORKSPACE pytest tests/unit tests/integration
