name: Transformations Dry Run

on:
  pull_request:
    paths:
      - "transformations/sql/**"
      - "scripts/run_transformations.py"
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Write GCP credentials file
        run: echo "${{ secrets.GCP_SA_KEY_JSON }}" > /tmp/gcp-key.json
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auth to GCP (OIDC)
        if: vars.BQ_PROJECT != ''
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_VERIFIER_SA }}
          token_format: access_token
      - name: Dry run compile
        run: |
          TODAY=$(date -u +%F)
          # Use vars.BQ_PROJECT if available, otherwise use placeholder for dry run
          PROJECT="${{ vars.BQ_PROJECT || 'dry-run-project-placeholder' }}"
          python scripts/run_transformations.py --project "$PROJECT" --dataset sensors --date "$TODAY"
